name: clang-format Check
on:
  pull_request:
    branches: ["*", "**"]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Run clang-format
      run: |
        SOURCE_DIR="src"
        FORMAT_ERRORS=0
        find "$SOURCE_DIR" -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.tpp" \) | while read -r FILENAME; do
          if ! clang-format -output-replacements-xml "$FILENAME" | grep -q "<replacement "; then
            echo "$FILENAME is not formatted correctly"
            FORMAT_ERRORS=1
          fi
        done
        exit $FORMAT_ERRORS